services:
  database:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: somethingsecret
      POSTGRES_USER: gram
    # ports <dont enable this unless you change passwords to something secure>:
    #   - 127.0.0.1:5432:5432
  gram:
    build: .
    restart: unless-stopped
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: gram
      POSTGRES_PASSWORD: somethingsecret
      POSTGRES_DB: gram
      POSTGRES_PORT: 5432
      SERVICE_STAGE: default # i.e. prod/staging for non-demo purposes
      AUTH_SECRET: <some long secret used to sign auth tokens>
      CSRF_SECRET: <similar but for csrf>
      GITHUB_APPID: <> # TODO: find a good way to have these optional/dynamic secrets.
      GITHUB_CLIENTID: <>
      GITHUB_CLIENTSECRET: <>
      GITHUB_PRIVATEKEY: <>
    ports:
      - 127.0.0.1:4726:8080

networks:
  default:
    name: gram-demo
